import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import DropMenu from "@/components/DropMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  { id: 1, label: "Image", children: [{ id: 11, label: "Hover Effect" }] },
  { id: 2, label: "Slider" },
  { id: 3, label: "Particles" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="ko">
      <body>
        <header className="p-4 bg-gray-800">
          <div className="container mx-auto">
            <h1 className="text-xl font-bold">My Application</h1>
            <nav className="mt-4">
              
            </nav>
          </div>
        </header>
        <main className="container mx-auto p-4">

        <DropMenu items={menuItems}/>
          {children}


        </main>
        <footer className="p-4 bg-gray-800 text-white text-center">
          © 2024 My Application
        </footer>
      </body>
    </html>
  );
}
