import type { Metadata } from "next";
import "./globals.css";
import HeaderComponent from "@/components/HeaderComponent";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="ko">
      <body>
      <HeaderComponent/>
        
        <main>
        
          {children}


        </main>
        {/* <footer className="p-4 bg-gray-800 text-white text-center">
          © 2024 My Application
        </footer> */}
      </body>
    </html>
  );
}
